import type { Metadata } from "next";
import "../globals.css";
import { getServerSession } from "next-auth";
import { Navbar } from "../components/navbar";
import Footer from "../components/footer";
import { authOptions } from "@/lib/auth";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const session = await getServerSession(authOptions);
  const user = session?.user ?? undefined;

  return (
      <div
      >
      <Navbar user={user} />
        {children}
        <Footer/>
      </div>
  );
}
